services:
  webserver:
    environment:
      VIDEO_API_SECRET: "${VIDEBO_EXTERNAL_API_SECRET:-secure}"
    ports:
      # Videbo storage and distributor ports (web port comes from webserver.port.yml).
      - "9020:9020"
      - "9030:9030"

  videbo:
    image: "videbo:latest"
    environment:
      VIDEBO_EXTERNAL_API_SECRET: "${VIDEBO_EXTERNAL_API_SECRET:-secure}"
      VIDEBO_LMS__API_URLS: "http://${MOODLE_DOCKER_WEB_HOST}/mod/videoservice/api.php"
      VIDEBO_DISTRIBUTOR: 1
    volumes:
      - "videbo-files:/videbo"
    network_mode: "service:webserver"

volumes:
  videbo-files:

